### ISSUE TITLE
Crash when exiting -- seems related to telnet, duppy and restart

### ISSUE THREAD

**Issue by dbaelde** [savonet/liquidsoap#160]
I was running a (simplified version of) the test in #149, with both telnet and socket enabled. When quitting with Ctrl-C, I obtained:

```
2014/03/21 08:06:40 [threads:2] Queue non-blocking queue #2 crashed with exception Bad file descriptor in select()
2014/03/21 08:06:40 [threads:2] Raised by primitive operation at file "list.ml", line 0, characters 0-0
Re-raised at file "duppy.ml", line 199, characters 17-18
Called from file "duppy.ml", line 201, characters 4-8
Called from file "duppy.ml", line 295, characters 12-25
Called from file "tools/tutils.ml", line 209, characters 13-61
```

This is not deterministic. I could reproduce twice, both times after a successful telnet connection. A potential culprit is the at_stop task which has been added for restart which closes the telnet socket... maybe before the duppy queue has stopped?

Duppy version is  917fbea8371ab3ae7c5f71204dd4b9ed2d462132 and liquidsoap is 05fc245e72d87d4b87d00f867fd06b62c95abba0.

**Comment by jdbuys** [comment]
I'm also experiencing this issue now and then, but I can't reproduce it. Any news on this?

**Comment by toots** [comment]
Yes, this should have been fixed with `1.2.1` actually. Gonna close, please reopen if you're experiencing it with that version. Thanks!

**Comment by jdbuys** [comment]
Thanks, I will upgrade to 1.2.1 and let you know

**Comment by jdbuys** [comment]
I upgraded to 1.2.1 and I am still experiencing the issue. It happens about once a day, but I can't replicate it. It doesn't seem like the exact same issue, so I can open a new issue if you like?

Here's a part of my log file:

016/07/26 02:07:53 [cue_cut_5994:3] Cueing out...
2016/07/26 02:07:53 [amplify_6021:3] End of the current overriding.
2016/07/26 02:07:53 [threads:2] Queue generic queue #1 crashed with exception Invalid argument in select()
2016/07/26 02:07:53 [threads:2] Re-raised at file "duppy.ml", line 199, characters 17-18
Called from file "duppy.ml", line 201, characters 4-8
Called from file "duppy.ml", line 295, characters 12-25
Called from file "tools/tutils.ml", line 206, characters 19-55

2016/07/26 02:07:53 [threads:1] PANIC: Liquidsoap has crashed, exiting..
2016/07/26 02:07:53 [threads:1] Please report at: savonet-users@lists.sf.net
2016/07/26 02:07:54 >>> LOG START

**Comment by jdbuys** [comment]
Hi, any news on this issue?

**Comment by jdbuys** [comment]
I am still experiencing this issue on 1.3.2

`2017/09/14 08:42:20 [buffer_12105:4] End of track.
2017/09/14 08:42:20 [buffer_12105:4] Buffer emptied, buffering needed.
2017/09/14 08:42:34 [server:4] Broken pipe in write()
2017/09/14 08:44:29 [server:4] Broken pipe in write()
2017/09/14 08:44:29 [threads:2] Queue generic queue #2 crashed with exception Invalid argument in select()
Re-raised at file "duppy.ml", line 199, characters 17-18
Called from file "duppy.ml", line 201, characters 4-8
Called from file "duppy.ml", line 295, characters 12-25
Called from file "tools/tutils.ml", line 213, characters 19-55
`

**Comment by toots** [comment]
Hey @jdbuys,

I want to look at this one when I have time. Do you have more info on your script?

Thanks,
Romain

**Comment by jdbuys** [comment]
Hey @toots 
Here's my script.
`#!/usr/local/bin/liquidsoap
set("log.file.path","radio.log")
set("log.stdout", true)
set("server.telnet",false)
set("server.socket",true)
set("server.socket.path","lsoap.sock")
set("server.socket.permissions",511)
set("server.timeout",20.)
set("scheduler.generic_queues",2)
set("scheduler.non_blocking_queues",2)
set("scheduler.fast_queues",0)
set("scheduler.log",true)
set("init.catch_exn",true)

delay = ref 3.
#Add error handler
def error_handler(the_error)=
  ignore(interactive.string("error_value",the_error))
  if string.match(pattern="401",the_error) == true then
    delay := 30.
  else
    delay := !delay
  end
  !delay
end

enable_external_faad_decoder()
#Add ffmpeg
def test_ffmpeg(file) = -1 end
ffmpeg_p = "/usr/local/bin/ffmpeg -i - -f wav -"
add_decoder(name="FFMPEG",description="Decode files using the ffmpeg decoder binary",mimes=["audio/aacp","application/octet-stream","audio/x-wav"],test=test_ffmpeg,ffmpeg_p)


source=fallback(track_sensitive=false,[playlist("/tmp/playlist.pls"),request.queue(id="queue",length=10.0),request.equeue(id="equeue")])
source=mksafe(source)
add_skip_command(source)
source=audio_to_stereo(id="source",source)



output.icecast(%mp3(stereo=true,bitrate=64,samplerate=44100),id="icecast",host="127.0.0.1",port=80,user="source",password="hackme",fallible=true,on_error=error_handler,name="Test",description="Test",mount="idGreenMonkeyUnited",url="http://test.com",source)`

Here's a snapshot of the log the last time the error occurred.

> 2017/10/07 12:57:51 [decoder.external:3] Starting process
2017/10/07 12:57:51 [queue:3] Prepared "/tmp/foo1.wma" (RID 4).
2017/10/07 12:57:51 [threads:2] Queue non-blocking queue #2 crashed with exception Invalid argument in select()
Re-raised at file "duppy.ml", line 199, characters 17-18
Called from file "duppy.ml", line 201, characters 4-8
Called from file "duppy.ml", line 295, characters 12-25
Called from file "tools/tutils.ml", line 215, characters 13-61

> 2017/10/07 12:57:51 [threads:1] PANIC: Liquidsoap has crashed, exiting.,
Please report at: savonet-users@lists.sf.net
2017/10/07 12:57:52 >>> LOG START

It happens very randomly and not very often.

Thanks,

JD

**Comment by toots** [comment]
Thanks for this! I'm gonna review the code. Could you also add:
```
set("log.level",4)
```
to your script? That would give us more information about what is going on when the crash occurs.

**Comment by toots** [comment]
Hi,

I'll try to have another pass at this shortly. Any luck getting a more verbose log?
