### ISSUE TITLE
`mksafe(input.rtmp(…))` hangs on shutdown

### ISSUE THREAD

**Issue by copy** [savonet/liquidsoap#2089]
**Describe the bug**

The following script hangs when exiting using ctrl+c when in safe_blank mode. Once the rtmp connection is accepted shutdown works fine. Once hanging the script needs to be killed with SIGKILL, it doesn't respond to other signals. I can also reproduce the issue with other outputs.

**To Reproduce**

```
output.sdl(mksafe(input.rtmp("rtmp://127.0.0.1:53163/share")))
```

Prints:

```
fabian@nyu /tmp % ~/.opam/lqs/bin/liquidsoap -v ./test
2021/12/05 21:12:04 >>> LOG START
2021/12/05 21:12:04 [main:3] Liquidsoap 2.0.0
2021/12/05 21:12:04 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.5.0 sedlex=2.4 menhirLib=20211125 dtools=0.4.4 duppy=0.9.2 mm=0.7.2 dynlink=[distributed with Ocaml] ffmpeg-avutil=1.0.1 ffmpeg-avcodec=1.0.1 ffmpeg-avdevice=1.0.1 ffmpeg-av=1.0.1 ffmpeg-avfilter=1.0.1 ffmpeg-swresample=1.0.1 ffmpeg-swscale=1.0.1 alsa=0.3.0 camomile=1.0.2 pulseaudio=0.1.4 tsdl=v0.9.8 tsdl-image=0.3.0 srt.constants=0.2.0 srt.types=0.2.0 srt.stubs=0.2.0 srt.stubs.locked=0.2.0 srt=0.2.0
2021/12/05 21:12:04 [dynamic.loader:3] Could not find dynamic module for lame encoder.
2021/12/05 21:12:04 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2021/12/05 21:12:04 [clock:3] Using builtin (low-precision) implementation for latency control
2021/12/05 21:12:04 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2021/12/05 21:12:04 [frame:3] Video frame size set to: 1280x720
2021/12/05 21:12:04 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2021/12/05 21:12:04 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/12/05 21:12:04 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/12/05 21:12:04 [sandbox:3] Sandboxing disabled
2021/12/05 21:12:04 [video.converter:3] Using preferred video converter: ffmpeg.
2021/12/05 21:12:04 [audio.converter:3] Using samplerate converter: ffmpeg.
2021/12/05 21:12:04 [clock.main:3] Streaming loop starts in auto-sync mode
2021/12/05 21:12:04 [clock.main:3] Delegating synchronisation to CPU clock
2021/12/05 21:12:04 [mksafe:3] Switch to safe_blank.
^C2021/12/05 21:12:07 [main:3] Shutdown started!
2021/12/05 21:12:07 [main:3] Waiting for main threads to terminate...
2021/12/05 21:12:07 [clock.main:3] Streaming loop stopped.
2021/12/05 21:12:07 [main:3] Main threads terminated.
2021/12/05 21:12:07 [threads:3] Shutting down scheduler...
```

**Expected behavior**

I expect a clean shutdown. In particular, when outputting to twitch, killing the script causes twitch to show a disconnection protection screen for a minute after the end of the stream.

**Version details**

See the log.

**Install method**

opam

**Comment by toots** [comment]
Thanks for this report. I will have a look at it as part of the `2.0.2` release cycle.

**Comment by toots** [comment]
This is now fixed! You can grab the `v2.0.2-preview` branch or the binary builds, for instance here: https://github.com/savonet/liquidsoap/actions/runs/1594433189

**Comment by copy** [comment]
@toots Thanks! I don't think I can test this at the moment: The v2.0.2-preview branch has a conflict on the latest versions of the `ffmpeg-*` libraries, but those don't seem be in the upstream repository yet (I tried pinning to master in https://github.com/savonet/ocaml-ffmpeg)

**Comment by toots** [comment]
Just bumped the opam versions!

**Comment by copy** [comment]
@toots Thanks! I compiled it, but my example above now seems to cause a segmentation fault (with liquidsoap pinned to v2.0.2-preview and ffmpeg-* pinned to master.

Here's a log:

```
% liquidsoap test.liquidsoap
2021/12/24 00:47:16 >>> LOG START
2021/12/24 00:47:15 [main:3] Liquidsoap 2.0.2+git@ce4dd577fe84
2021/12/24 00:47:15 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.5.0 sedlex=2.5 menhirLib=20211128 dtools=0.4.4 duppy=0.9.2 mm=0.7.2 dynlink=[distributed with Ocaml] ffmpeg-avutil=5b0ab162f977 ffmpeg-avcodec=5b0ab162f977 ffmpeg-avdevice=5b0ab162f977 ffmpeg-av=5b0ab162f977 ffmpeg-avfilter=5b0ab162f977 ffmpeg-swresample=5b0ab162f977 ffmpeg-swscale=5b0ab162f977 alsa=0.3.0 camomile=1.0.2 pulseaudio=0.1.4 tsdl=v0.9.8 tsdl-image=0.3.1
2021/12/24 00:47:15 [main:3] 
2021/12/24 00:47:15 [main:3] DISCLAIMER: This version of Liquidsoap has been
2021/12/24 00:47:15 [main:3] compiled from a snapshot of the development code.
2021/12/24 00:47:15 [main:3] As such, it should not be used in production
2021/12/24 00:47:15 [main:3] unless you know what you are doing!
2021/12/24 00:47:15 [main:3] 
2021/12/24 00:47:15 [main:3] We are, however, very interested in any feedback
2021/12/24 00:47:15 [main:3] about our development code and committed to fix
2021/12/24 00:47:15 [main:3] issues as soon as possible.
2021/12/24 00:47:15 [main:3] 
2021/12/24 00:47:15 [main:3] If you are interested in collaborating to
2021/12/24 00:47:15 [main:3] the development of Liquidsoap, feel free to
2021/12/24 00:47:15 [main:3] drop us a mail at <savonet-devl@lists.sf.net>
2021/12/24 00:47:15 [main:3] or to join the slack chat at <http://slack.liquidsoap.info>.
2021/12/24 00:47:15 [main:3] 
2021/12/24 00:47:15 [main:3] Please send any bug report or feature request
2021/12/24 00:47:15 [main:3] at <https://github.com/savonet/liquidsoap/issues>.
2021/12/24 00:47:15 [main:3] 
2021/12/24 00:47:15 [main:3] We hope you enjoy this snapshot build of Liquidsoap!
2021/12/24 00:47:15 [main:3] 
2021/12/24 00:47:15 [dynamic.loader:3] Could not find dynamic module for lame encoder.
2021/12/24 00:47:15 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2021/12/24 00:47:15 [clock:3] Using builtin (low-precision) implementation for latency control
2021/12/24 00:47:16 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2021/12/24 00:47:16 [frame:3] Video frame size set to: 1280x720
2021/12/24 00:47:16 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2021/12/24 00:47:16 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/12/24 00:47:16 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/12/24 00:47:16 [sandbox:3] Sandboxing disabled
2021/12/24 00:47:16 [video.converter:3] Using preferred video converter: ffmpeg.
2021/12/24 00:47:16 [audio.converter:3] Using samplerate converter: ffmpeg.
2021/12/24 00:47:16 [clock.main:3] Streaming loop starts in auto-sync mode
2021/12/24 00:47:16 [clock.main:3] Delegating synchronisation to CPU clock
2021/12/24 00:47:16 [mksafe:3] Switch to safe_blank.
[1]    12717 segmentation fault (core dumped)  liquidsoap test-pulse.liquidsoap
```

And a backtrace:

```
% gdb liquidsoap 
Reading symbols from liquidsoap...
(gdb) run test.liquidsoap 
Starting program: …/.opam/lqs-2.0.2-preview/bin/liquidsoap test-pulse.liquidsoap
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after vfork from child process 12858]
2021/12/24 00:49:49 >>> LOG START
…
2021/12/24 00:49:49 [mksafe:3] Switch to safe_blank.
[New Thread 0x7fffbb87a640 (LWP 12868)]

Thread 7 "liquidsoap" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd6ffd640 (LWP 12865)]
0x0000000000000001 in ?? ()
(gdb) bt
#0  0x0000000000000001 in  ()
#1  0x0000555555d83b71 in caml_start_program ()
#2  0x0000555555d79a7a in caml_callback_exn (arg=<optimized out>, closure=140737038021040) at callback.c:111
#3  caml_callback (closure=closure@entry=140737038021040, arg=arg@entry=1) at callback.c:165
#4  0x0000555555d3c1bb in ocaml_av_interrupt_callback (private=0x7fffe52871b0) at av_stubs.c:380
#5  0x00007ffff7354982 in  () at /usr/lib/libavformat.so.58
#6  0x00007ffff73b9d62 in  () at /usr/lib/libavformat.so.58
#7  0x00007ffff7278c06 in  () at /usr/lib/libavformat.so.58
#8  0x00007ffff73ec08f in  () at /usr/lib/libavformat.so.58
#9  0x00007ffff7381087 in  () at /usr/lib/libavformat.so.58
#10 0x00007ffff7278a8b in  () at /usr/lib/libavformat.so.58
#11 0x00007ffff727940f in  () at /usr/lib/libavformat.so.58
#12 0x00007ffff736b63b in  () at /usr/lib/libavformat.so.58
#13 0x00007ffff73c66f3 in avformat_open_input () at /usr/lib/libavformat.so.58
#14 0x0000555555d3c2d4 in open_input
    (url=url@entry=0x7fffcc004bc0 "rtmp://127.0.0.1:53163/share", format=0x7ffff74a02a0, format_context=format_context@entry=0x0, _interrupt=140737038021024, options=options@entry=0x7fffd6ffc118)
    at av_stubs.c:587
#15 0x0000555555d3e2b2 in ocaml_av_open_input (_url=<optimized out>, _format=<optimized out>, _interrupt=<optimized out>, _opts=<optimized out>) at av_stubs.c:649
#16 0x0000555555bffb66 in camlAv__open_input_192 () at av/av.ml:59
#17 0x0000555555977f6f in camlFfmpeg_io__fun_3314 () at io/ffmpeg_io.ml:88
#18 0x0000555555c94e46 in camlDuppy__task_638 () at src/duppy.ml:393
#19 0x0000555555c9374c in camlDuppy__fun_2412 () at src/duppy.ml:148
#20 0x0000555555c94430 in camlDuppy__exec_585 () at src/duppy.ml:275
#21 0x0000555555c9487b in camlDuppy__f_618 () at src/duppy.ml:307
#22 0x0000555555c94683 in camlDuppy__queue_inner_2548 () at src/duppy.ml:357
#23 0x0000555555b5fef7 in camlTutils__process_731 () at tools/tutils.ml:175
#24 0x0000555555cc46e5 in camlThread__fun_314 () at thread.ml:41
#25 0x0000555555d83b71 in caml_start_program ()
#26 0x0000555555d7978d in caml_callback_exn (closure=closure@entry=140737038047424, arg=<optimized out>, arg@entry=1) at callback.c:111
#27 0x0000555555d59e00 in caml_thread_start (arg=0x7fffd0006600) at st_stubs.c:547
#28 0x00007ffff5d4a259 in start_thread () at /usr/lib/libpthread.so.0
#29 0x00007ffff5b285e3 in clone () at /usr/lib/libc.so.6
```

**Comment by copy** [comment]
Seems to be related to `input.rtmp`. It also segfaults with `output.dummy` but not with only a `single` input.

**Comment by toots** [comment]
Yeah, this was fixed in https://github.com/savonet/ocaml-ffmpeg/commit/38f651ad1a1b92eb2ee33bd9e1b6aa9911e5e332 I believe

**Comment by copy** [comment]
@toots I see, thanks! Now it runs, but the original issue is still present:

```
2021/12/24 11:49:13 >>> LOG START
2021/12/24 11:49:11 [main:3] Liquidsoap 2.0.2+git@ce4dd577fe84
2021/12/24 11:49:11 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.5.0 sedlex=2.5 menhirLib=20211128 dtools=0.4.4 duppy=0.9.2 mm=0.7.2 dynlink=[distributed with Ocaml] ffmpeg-avutil=38f651ad1a1b ffmpeg-avcodec=38f651ad1a1b ffmpeg-avdevice=38f651ad1a1b ffmpeg-av=38f651ad1a1b ffmpeg-avfilter=38f651ad1a1b ffmpeg-swresample=38f651ad1a1b ffmpeg-swscale=38f651ad1a1b alsa=0.3.0 camomile=1.0.2 pulseaudio=0.1.4 tsdl=v0.9.8 tsdl-image=0.3.2
2021/12/24 11:49:11 [main:3] 
2021/12/24 11:49:11 [main:3] DISCLAIMER: This version of Liquidsoap has been
2021/12/24 11:49:11 [main:3] compiled from a snapshot of the development code.
2021/12/24 11:49:11 [main:3] As such, it should not be used in production
2021/12/24 11:49:11 [main:3] unless you know what you are doing!
2021/12/24 11:49:11 [main:3] 
2021/12/24 11:49:11 [main:3] We are, however, very interested in any feedback
2021/12/24 11:49:11 [main:3] about our development code and committed to fix
2021/12/24 11:49:11 [main:3] issues as soon as possible.
2021/12/24 11:49:11 [main:3] 
2021/12/24 11:49:11 [main:3] If you are interested in collaborating to
2021/12/24 11:49:11 [main:3] the development of Liquidsoap, feel free to
2021/12/24 11:49:11 [main:3] drop us a mail at <savonet-devl@lists.sf.net>
2021/12/24 11:49:11 [main:3] or to join the slack chat at <http://slack.liquidsoap.info>.
2021/12/24 11:49:11 [main:3] 
2021/12/24 11:49:11 [main:3] Please send any bug report or feature request
2021/12/24 11:49:11 [main:3] at <https://github.com/savonet/liquidsoap/issues>.
2021/12/24 11:49:11 [main:3] 
2021/12/24 11:49:11 [main:3] We hope you enjoy this snapshot build of Liquidsoap!
2021/12/24 11:49:11 [main:3] 
2021/12/24 11:49:11 [dynamic.loader:3] Could not find dynamic module for lame encoder.
2021/12/24 11:49:11 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2021/12/24 11:49:11 [clock:3] Using builtin (low-precision) implementation for latency control
2021/12/24 11:49:12 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2021/12/24 11:49:12 [frame:3] Video frame size set to: 1280x720
2021/12/24 11:49:12 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2021/12/24 11:49:12 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/12/24 11:49:12 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/12/24 11:49:12 [sandbox:3] Sandboxing disabled
2021/12/24 11:49:12 [video.converter:3] Using preferred video converter: ffmpeg.
2021/12/24 11:49:12 [audio.converter:3] Using samplerate converter: ffmpeg.
2021/12/24 11:49:13 [clock.main:3] Streaming loop starts in auto-sync mode
2021/12/24 11:49:13 [clock.main:3] Delegating synchronisation to CPU clock
2021/12/24 11:49:13 [mksafe:3] Switch to safe_blank.
^C2021/12/24 11:49:18 [main:3] Shutdown started!
2021/12/24 11:49:18 [main:3] Waiting for main threads to terminate...
2021/12/24 11:49:18 [clock.main:3] Streaming loop stopped.
2021/12/24 11:49:18 [main:3] Main threads terminated.
2021/12/24 11:49:18 [threads:3] Shutting down scheduler...
```

**Comment by toots** [comment]
🤦 

This is fixed now, thanks for your patience. I've added a regression test to catch it if it happens again..

**Comment by copy** [comment]
Thanks a lot! All working now.

**Comment by copy** [comment]
@toots Sorry to have to bother you again. In 2.0.2 the script doesn't switch from safe_blank to the rtmp stream any more (the `rtmp @ 0x7f0bc4003a00` message appears when I start the rtmp input):

```
% liquidsoap -v 'output.sdl(mksafe(input.rtmp("rtmp://127.0.0.1:53163/share")))'
2021/12/31 17:06:06 >>> LOG START
2021/12/31 17:06:05 [main:3] Liquidsoap 2.0.2
2021/12/31 17:06:05 [main:3] Using: bytes=[distributed with OCaml 4.02 or above] pcre=7.5.0 sedlex=2.5 menhirLib=20211230 dtools=0.4.4 duppy=0.9.2 mm=0.7.2 dynlink=[distributed with Ocaml] ffmpeg=1.1.1 alsa=0.3.0 camomile=1.0.2 pulseaudio=0.1.4 tsdl=v0.9.8 tsdl-image=0.3.2
2021/12/31 17:06:05 [dynamic.loader:3] Could not find dynamic module for lame encoder.
2021/12/31 17:06:05 [dynamic.loader:3] Could not find dynamic module for fdkaac encoder.
2021/12/31 17:06:05 [clock:3] Using builtin (low-precision) implementation for latency control
2021/12/31 17:06:06 [frame:3] Using 44100Hz audio, 25Hz video, 44100Hz main.
2021/12/31 17:06:06 [frame:3] Video frame size set to: 1280x720
2021/12/31 17:06:06 [frame:3] Frame size must be a multiple of 1764 ticks = 1764 audio samples = 1 video samples.
2021/12/31 17:06:06 [frame:3] Targeting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
2021/12/31 17:06:06 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
2021/12/31 17:06:06 [sandbox:3] Sandboxing disabled
2021/12/31 17:06:06 [video.converter:3] Using preferred video converter: ffmpeg.
2021/12/31 17:06:06 [audio.converter:3] Using samplerate converter: ffmpeg.
2021/12/31 17:06:06 [clock.main:3] Streaming loop starts in auto-sync mode
2021/12/31 17:06:06 [clock.main:3] Delegating synchronisation to CPU clock
2021/12/31 17:06:06 [mksafe:3] Switch to safe_blank.
2021/12/31 17:06:11 [clock.main:2] We must catchup 0.12 seconds!
2021/12/31 17:06:14 [clock.main:2] We must catchup 0.07 seconds!
2021/12/31 17:06:18 [clock.main:2] We must catchup 0.00 seconds!
[rtmp @ 0x7f0bc4003a00] Unexpected stream , expecting share
[rtmp @ 0x7f0bc4003a00] Unexpected stream , expecting share
2021/12/31 17:06:33 [clock.main:2] We must catchup 0.10 seconds!
2021/12/31 17:06:37 [clock.main:2] We must catchup 0.11 seconds!
2021/12/31 17:06:41 [clock.main:2] We must catchup 0.14 seconds!
2021/12/31 17:06:45 [clock.main:2] We must catchup 0.27 seconds!
2021/12/31 17:06:50 [clock.main:2] We must catchup 0.72 seconds!
2021/12/31 17:06:53 [clock.main:2] We must catchup 1.01 seconds!
2021/12/31 17:06:54 [clock.main:2] We must catchup 1.21 seconds!
2021/12/31 17:06:55 [clock.main:2] We must catchup 1.26 seconds!
2021/12/31 17:06:56 [clock.main:2] We must catchup 1.26 seconds!
2021/12/31 17:06:57 [clock.main:2] We must catchup 1.26 seconds!
2021/12/31 17:06:58 [clock.main:2] We must catchup 1.30 seconds!
2021/12/31 17:06:59 [clock.main:2] We must catchup 1.29 seconds!
2021/12/31 17:07:00 [clock.main:2] We must catchup 1.29 seconds!
2021/12/31 17:07:01 [clock.main:2] We must catchup 1.28 seconds!
2021/12/31 17:07:02 [clock.main:2] We must catchup 1.29 seconds!
2021/12/31 17:07:03 [clock.main:2] We must catchup 1.29 seconds!
^C2021/12/31 17:07:04 [main:3] Shutdown started!
2021/12/31 17:07:04 [main:3] Waiting for main threads to terminate...
2021/12/31 17:07:04 [clock.main:3] Streaming loop stopped.
2021/12/31 17:07:04 [main:3] Main threads terminated.
2021/12/31 17:07:04 [threads:3] Shutting down scheduler...
2021/12/31 17:07:04 [threads:3] Scheduler shut down.
2021/12/31 17:07:04 [main:3] Cleaning downloaded files...
2021/12/31 17:07:04 [main:3] Freeing memory...
```

**Comment by toots** [comment]
This might be a problem with the SDL output. This also works fine:
```ruby
output.file(
  %ffmpeg(
    format="mp4",
    %audio(codec="libmp3lame"),
    %video(codec="libx264")
  ),
  "/tmp/bla.mp4",
  mksafe(input.rtmp("rtmp://0.0.0.0:1935/input"))
)
```
