### ISSUE TITLE
Liquidsoap crash when I switch url on input.http with ogg vorbis stream

### ISSUE THREAD

**Issue by oskarburman** [savonet/liquidsoap#2956]
**Describe the bug**
I have a script that allows me to change stream url dynamically. It works quite well when I am streaming mp3 but when I use an ogg stream the memory usage start to rise, but it doesn't crash until I change the url and run: `<http-source>.stop()`

Depending on the setup (os and liquidsoap version) the memory usage is stable on around 400MB until I start an ogg stream. Then it slowly rises (latest case it was at 489MB) and if I try to switch I get this from dmesg:
`liquidsoap[50332]: segfault at 4b0 ip 0000562afff733ed sp 00007f36af7fca50 error 4 in liquidsoap[562aff7f6000+7e7000]`

I have run it with strace and gdb and get `memcpy-ssse3.s no such file or directory`.

It seams like it eats the stream to slowly and the buffer gets to big to handle a fork. But that is only me guessing, probably wrong :-)

The ogg stream that is involved in the the crash is produced with liquidsoap 2.0.0 in Docker and 1.3.3 on a Raspberry Pi.

I also get a lot of:
```
[alsa_out(plughw:1):2] Underrun!
[alsa_out(plughw:1):2] Trying to recover.
```

And sometimes:
```
[input.http_0:2] Feeding failed: Ffmpeg_decoder.End_of_file
```
But that is probably not connected to the crash.

Liquidsoap does not say anything when it crashes. The memory thing could be unrelated but... 

Sometimes it runs well for an hour or so. But eventually it starts to behave like this.

**To Reproduce**
this one is for Liquidsoap 2.2.0 but I have the same result with 2.1.3 (without interactive.unit)

```
audioIn1 = mksafe(input.alsa(clock_safe=true, device="plughw:1"))
selectLineIn1 = interactive.bool("selectLineIn1", false)
selectStream1 = interactive.bool("selectStream1", true)
streamUrl = interactive.string("streamUrl", "http://http-live.sr.se/p3-mp3-128")

audioStream1 = input.http(self_sync=true, "http://http-live.sr.se/p3-mp3-128")

mainStream = switch(track_sensitive=false,[
(selectLineIn1,audioIn1),
(selectStream1,audioStream1),
])

def changeStreamFunc() =
	  audioStream1.stop()
	  audioStream1.set_url(streamUrl())
	  audioStream1.start()
end

changeStream = interactive.unit("change", changeStreamFunc)
interactive.harbor()
output.icecast(%mp3.cbr(samplerate=48000, bitrate=128), host = "localhost", port = 22003, password = "secret", mount = "live.mp3", mainStream)
output.alsa(clock_safe=false, bufferize=true, device="plughw:1", mainStream)
```

Go to `http://<ip>:8000/interactive` and change the stream to some ogg-vorbis stream and push "change" button.
Run "smem -k" and you will see memory usage rising.

**Expected behavior**
No memory usage rise and no crash.

**Version details**
Debian bullseye, Raspbian Bullseye, Liqudsoap version 2.1.3, 2.1.4, d1206cf_2.2.0

**Install method**
Downloaded deb package from github

**Comment by toots** [comment]
Hi @oskarburman and thanks for reporting. The memory increase could be due to a synchronization issue between the alsa clock and the http live stream. 

Have you tried to run the script without the alsa input and output? For instance using a `single` input and no alsa output?

**Comment by oskarburman** [comment]
I removed alsa in/out and the switch statement. Kept the url-changeing stuff. The result is worse, now it segfaults almost immediately and even when I change between mp3 streams. I also removed "self_sync=true" but that didn't help. Only tested with d1206cf_2.2.0 this time.

You mentioned to use a "single", do you mean to be able to keep the switch statement? Do you still want me to test that?

**Comment by toots** [comment]
Yes, pruning down the reproduction case to figure out the minimal context would help a lot debugging and figuring out the root cause of the issue.

You could try this:
```
s = input.http(self_sync=true, "http://http-live.sr.se/p3-mp3-128")

def changeStreamFunc() =
	  s.stop()
	  s.set_url(streamUrl())
	  s.start()
end

interactive.unit("change", changeStreamFunc)
interactive.harbor()

output.dummy(fallible=true, s)
```

**Comment by oskarburman** [comment]
I get segmentation fault with this one too.

**Comment by toots** [comment]
This was fixed with #2992

**Comment by toots** [comment]
Sorry I forgot #2992 wasn't merged yet.. 😅

**Comment by oskarburman** [comment]
Sorry to bother you... Has this made it to the rolling release? I can't see it there. (And the latest release still crashes)

**Comment by toots** [comment]
It should be on the latest `rolling-release-v2.2.x` now and `main` of course. I'm not sure about backporting to `rolling-release-v2.1.x`, the code for this operator has changed a bunch since. Could `rolling-release-v2.2.x` work for you?

**Comment by toots** [comment]
Thanks. The build failed, I've re-queued another one. There is indeed a mention of the bug fix in the changelog:
```
* Fixed race condition when switching input.ffmpeg-based urls (#2956)
```

**Comment by oskarburman** [comment]
Yes it is in the main branch changes file. But not in the rolling-release-v2.2.x changes. (I just mentioned that as an indication of that it is not in current release.) When do you think the next rolling-release-v2.2.x with docker and .deb packages will be built? Current one is two weeks old.

**Comment by toots** [comment]
There was an unrelated bug preventing the build from finishing. Should be fixed now.

**Comment by oskarburman** [comment]
Thank you!
This is better, but ...

It has not crashed yet if I have an alsa output. But with dummy:

Sometimes when I push the Change button it works and the log prints this:
2023/04/27 09:21:26 [clock.main:3] Delegating synchronisation to active sources
2023/04/27 09:21:29 [input.http_0:2] Feeding failed: Ffmpeg_io.Not_connected
2023/04/27 09:21:29 [dummy:3] Source failed (no more tracks) stopping output...
2023/04/27 09:21:29 [clock.main:3] Delegating synchronisation to CPU clock
...

But most times this happens:
2023/04/27 09:21:29 [clock.main:3] Delegating synchronisation to active sources
2023/04/27 09:21:30 [input.http_0:2] Feeding failed: Invalid_argument("option is None")
2023/04/27 09:21:30 [input.http_0:2] #get_frame didn't add exactly one break!
2023/04/27 09:21:30 [clock.main:2] Source dummy failed while streaming: File "src/core/source.ml", line 732, characters 14-20: Assertion failed!
2023/04/27 09:21:30 [clock.main:2] Raised at Source.operator#get in file "src/core/source.ml", line 732, characters 14-26
2023/04/27 09:21:30 [clock.main:2] Called from Output.output#output in file "src/core/outputs/output.ml", line 166, characters 10-30
2023/04/27 09:21:30 [clock.main:2] Called from Clock.MkClock.clock#end_tick.(fun) in file "src/core/clock.ml", line 305, characters 16-24

And then liquidsoap shutsdown gracefully

This is the script I am using:
s = input.http("http://http-live.sr.se/p3-mp3-128")
streamUrl = interactive.string("streamUrl", "http://http-live.sr.se/p3-mp3-128")

def changeStreamFunc() =
	  s.stop()
	  s.set_url(streamUrl())
	  s.start()
end

interactive.unit("change", changeStreamFunc)
interactive.harbor(port=8000)
output.dummy(fallible=true, s)

Liquidsoap 2.2.0+git@5d6889e7e

**Comment by oskarburman** [comment]
Actually this is enough for it to crash:

s = input.http("http://http-live.sr.se/p3-mp3-128")
def changeStreamFunc() =
          s.stop()
end
interactive.unit("change", changeStreamFunc)
interactive.harbor(port=8081)
output.dummy(fallible=true, s)

**Comment by toots** [comment]
Thanks for reporting. This is fixed in `main` and `rolling-release-v2.2.x`
