### ISSUE TITLE
v2.1.4: [input.harbor.ssl_0:2] Error while reading from client: Invalid argument in select()

### ISSUE THREAD

**Issue by brenc** [savonet/liquidsoap#3156]
**Describe the bug**
After updating to 2.1.4 we started to see this when a client connects to Harbor input:

[input.harbor.ssl_0:3] Decoding...
[input.harbor.ssl_0:2] Error while reading from client: Invalid argument in select()
[input.harbor.ssl_0:2] Feeding stopped: Avutil.Error(Invalid data found when processing input).

The client is then disconnected. The only thing that fixes this is restarting LS. This doesn't happen all the time. Seems something triggers it then after that no client can connect.

**To Reproduce**
Happens with a simple Harbor input, both SSL and non-SSL are affected.

```
let ngr.inputs.harbor = input.harbor(
  "radio",
  buffer=6.0,
  port=8003,
  timeout=10.0,
  user=icecast_mount_radio_usr,
  password=icecast_mount_radio_psw,
)
```

**Expected behavior**
Allow streaming clients to connect and stream.

**Version details**

- OS: Docker
- Version: savonet/liquidsoap:v2.1.4

**Install method**
Docker

**Comment by vitoyucepi** [comment]
Hi @brenc,
From which version did you upgrade?
Was it caused by a certain client, a single user, or a particular software?

**Comment by brenc** [comment]
From v2.1.3. We use butt to broadcast but this is happening with metadata updates as well:

```
[/radio.mp3:3] Metadata update may have failed with error: Invalid argument in select()
```

We haven't had any issues since reverting to 2.1.3.

**Comment by vitoyucepi** [comment]
I'm unable to reproduce the problem.
1. What's the operation system you're running docker on?
1. Which docker version are you using?
1. Could you share container run parameters?
1. How often this problem happens?
1. What are the encoding parameters used in the butt?

Maybe if you set `settings.log.level.set(6)`, then it will produce more information.

**Comment by brenc** [comment]
1. Debian 11 x64
2. Docker version 24.0.1, build 6802122
3. All we're doing is copying over some files and running `CMD ["/usr/bin/liquidsoap", "main.liq"]`
4. Something seems to trigger it but I don't know what. I will try increasing logging on staging and see if it logs anything else.
5. Stock 128k mp3.

Still no `select()` errors since rolling back to v2.1.3.

**Comment by vitoyucepi** [comment]
> Docker version 24.0.1, build 6802122

I should mention it earlier, but could you show the results of the `docker info` command?

> All we're doing is copying over some files and running CMD ["/usr/bin/liquidsoap", "main.liq"]

Is it `docker run -it --rm savonet/liquidsoap:v2.1.4`, or did I miss something? Maybe some network options?
You can post a *docker-compose* project if you're using it.

> Something seems to trigger it but I don't know what.

Docker can cause the problem.

> All we're doing is copying over some files

If you're building the container anyway, then why wouldn't you build it using `ubuntu:22.04` + deb package from release?

**Comment by brenc** [comment]
```
Client:                                 
 Context:    default       
 Debug Mode: false                      
 Plugins:                               
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4                   
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 20
  Running: 7
  Paused: 0
  Stopped: 13
 Images: 18
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: syslog
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk s
yslog
 Swarm: active
  NodeID: jqbmejv6mo0vdqthj4wety3hr
  Is Manager: true
  ClusterID: r26xd03m4b254wlxtsiock6oy
  Managers: 7
  Nodes: 7
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:                                                                [4/91266]
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1 
   Election Tick: 10 
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.10.1.57
  Manager Addresses: 
   10.10.1.19:2377
   10.10.1.54:2377
   10.10.1.55:2377
   10.10.1.56:2377
   10.10.1.57:2377
   10.10.1.58:2377
   10.10.1.59:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-22-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.78GiB
 Name: docker04
 ID: Z3WQ:TVQJ:OA33:LUUT:G4V4:TAAF:7MF7:6IFA:L5AU:PF2Q:Y6SW:MR2T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false 
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

> You can post a docker-compose project if you're using it.

We're using Docker Stack on enterprise servers. There isn't anything interesting or unusual in the stack file. It's setting env vars, telling it what image to use, opening ports, etc.

> Docker can cause the problem.

Hasn't before this 2.1.4 for us anyway.

> If you're building the container anyway, then why wouldn't you build it using ubuntu:22.04 + deb package from release?

Stock image works perfectly fine. No reason to use anything else.

**Comment by brenc** [comment]
OK - I have gathered some more data. I was able to recreate this on my dev box which is running the same (or very close) version of Docker. On dev I use Docker Compose which is set up to mimic prod as closely as possible (prod is using Swarm). I'm using haproxy to frontend all these connection and pass them off to the LS instance. Just a simple TCP proxy with minimal processing.

So I left butt streaming all night long and when I got up today it was still working fine. Then I disconnected and reconnected and was able to recreate this issue. When going through the proxy is takes about 50s before butt will disconnect. I believe the proxy server is buffering data but LS doesn't respond so once a timer is reached the proxy disconnects the client.

On dev I can bypass the proxy server so I did that. butt gets disconnected immediately and will reconnect over and over again until it eventually reconnects. Here are the logs LS produces (with `settings.log.level.set(6)`):

```
[harbor:4] PUT (source) request on /radio.
[harbor:4] Adding source on mountpoint "/radio" with type "audio/mpeg".
[harbor:5] Relaying HTTP/1.1.
[decoder:4] Available decoders:
[decoder:4] FFMPEG (priority: 10)
[decoder:4] MAD (priority: 1)
[decoder:4] Selected decoder FFMPEG for mime-type audio/mpeg with expected content {audio=pcm(stereo),video=none,midi=none}
[threads:4] Created thread "harbor source feeding" (2 total).
[input.harbor_0:3] Decoding...
[input.harbor_0:2] Error while reading from client: Invalid argument in select()
[input.harbor_0:2] Feeding stopped: Avutil.Error(Invalid data found when processing input).
[threads:4] Thread "harbor source feeding" terminated (1 remaining).
```

I see `select()` errors on metadata updates as well:

```
[replay_metadata_11:5] Got metadata at position 0: calling handlers...
[on_metadata_20:5] Got metadata at position 0: calling handler...
[on_metadata_20:5] Got metadata at position 0: calling handlers...
[replay_metadata_11:4] Fading in (type: sin, duration: 6.s).
[on_track_22:5] Got metadata at position 0: calling handlers...
[fade.in:5] Got metadata at position 0: calling handlers...
[fade.in:5] Got metadata at position 0: calling handlers...
[add_13:5] Got metadata at position 0: calling handlers...
[max_duration_13:5] Got metadata at position 0: calling handlers...
[sequence_20:5] Got metadata at position 0: calling handlers...
[switch_2:5] Got metadata at position 0: calling handlers...
[rms_2:5] Got metadata at position 0: calling handlers...
[lufs_0:5] Got metadata at position 0: calling handlers...
[bpm_0:5] Got metadata at position 0: calling handlers...
[mksafe:5] Got metadata at position 0: calling handlers...
[insert_metadata_0:5] Got metadata at position 0: calling handlers...
[max_duration_13:5] Content kind: {audio=pcm(stereo),video=none,midi=none}, content type: {audio=pcm(stereo),video=none,midi=none}
[sequence_19:5] Content kind: {audio=pcm(stereo),video=none,midi=none}, content type: {audio=pcm(stereo),video=none,midi=none}
[sequence_20:5] Content kind: {audio=pcm(stereo),video=none,midi=none}, content type: {audio=pcm(stereo),video=none,midi=none}
[ffmpeg.encode.audio.producer_0:5] Got metadata at position 0: calling handlers...
[/radio.mp3:3] Metadata update may have failed with error: Invalid argument in select()
[/radio.mp3:3] Metadata update may have failed with error: Invalid argument in select()
[/radio.mp3:3] Metadata update may have failed with error: Invalid argument in select()
[DEBUG]: ngr.inputs.update_live_status: input is now off-air
```

**Comment by vitoyucepi** [comment]
Maybe I'm doing something wrong, but I can't replicate this behavior.

I tried to fully reproduce your setup as far as I understand it.
1. Use debian 11 cloudimage x64.
1. Add docker upstream repos using the [official guide](https://docs.docker.com/engine/install/debian/).
1. Install packages.
   ```sh
   apt-get install --no-install-recommends \
     docker-ce=5:23.0.5-1~debian.11~bullseye \
     docker-ce-cli=5:24.0.1-1~debian.11~bullseye \
     docker-buildx-plugin=0.10.4-1~debian.11~bullseye \
     docker-compose-plugin=2.17.3-1~debian.11~bullseye
   ```
1. Create liquidsoap config.
   ```ruby
   settings.log.level.set(6)

   a = input.harbor(
     "radio",
     port=8001,
     user="source",
     password="hackme",
     buffer=6.0,
     timeout=10.0,
   )

   output.icecast(
     %mp3,
     mksafe(a),
     user="source",
     password="hackme",
     mount="/radio",
     host="icecast",
     port=8000,
   )
   ```
1. Run containers with the following compose config.
   ```yaml
   services:
     liquidsoap:
       image: savonet/liquidsoap:v2.1.4
       ports:
         - 8001:8001
       volumes:
         - ./liquidsoap/:/home/liquidsoap/
       command: "/home/liquidsoap/main.liq"
     icecast:
       image: registry.gitlab.com/vito-containers/icecast:2.4
       ports:
         - 8000:8000
       environment:
         ICECAST_AUTHENTICATION_SOURCE_PASSWORD: hackme
   ```
1. Connect with butt to `http://source:hackme@$IP:8001/radio`.

Did I miss something?

**Comment by brenc** [comment]
That looks correct yes. Like I said, it doesn't happen immediately. It has to run for a while then something triggers it. Once triggered a restart fixes it for a period of time.

**Comment by vitoyucepi** [comment]
I wonder if you can replicate the faulty behavior using the following command?
```sh
while true; do 
  ffmpeg \
    -re \
    -f lavfi \
    -i "sine=frequency=1000:duration=5" \
    -b:a 128k \
    -c:a mp3 \
    -f mp3 \
    "icecast://source:hackme@$IP:8001/radio";
done
```
This script will play 5 seconds of sine at 1000Hz in a loop. Replace `icecast://source:hackme@$IP:8001/radio` with your harbor parameters.

**Comment by vitoyucepi** [comment]
I'm not sure why, but so far I haven't experienced any issues.
After a day of connects (and disconnects), there were no errors.

<details>
<summary>If you have some free time, I can suggest additional methods to recreate the issue on my end.</summary>

> I was able to recreate this on my dev box

Can you create a disk image for a virtual machine that includes all the packages, containers, and scripts needed?

</details>

Alternatively, you could check if the error persists in `savonet/liquidsoap:rolling-release-v2.2.x`.

**Comment by brenc** [comment]
Yeah I've been thinking about how to create a minimal config to reproduce this. I think I have an idea. Will try to get something to you soon.

**Comment by vitoyucepi** [comment]
@brenc, could you share the values of `ulimit -a -S` and `ulimit -a -H`? Inside the liquidsoap container and in the system.
Did you check `journalctl`, maybe something happened there?

**Comment by brenc** [comment]
```
# ulimit -a -S
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 256745
max locked memory           (kbytes, -l) 8228984
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 256745
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited

# ulimit -a -H
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 256745
max locked memory           (kbytes, -l) 8228984
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) unlimited
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 256745
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

In the container:
```
$ ulimit -a -S
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 256745
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) unlimited
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited

$ ulimit -a -H
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 256745
max locked memory           (kbytes, -l) 64
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) unlimited
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) unlimited
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

No additional logs anywhere. I have a small API over Harbor that gets queried every second by the proxy servers and other processes. I think that is involved in triggering this.

**Comment by vitoyucepi** [comment]
Docker has a bug https://github.com/moby/moby/issues/38814

I'm not sure if this is related to the docker issue, but can you try setting limits in the dev environment and reproduce the problem?

```yaml
services:
  liquidsoap:
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
```
Reference documentation: https://docs.docker.com/compose/compose-file/compose-file-v3/#ulimits

**Comment by brenc** [comment]
I can't see how this would be a Docker issue considering 2.1.3 works but 2.1.4 does not.

**Comment by vitoyucepi** [comment]
I don't know either, but it looks suspicious.

https://github.com/moby/moby/issues/38814#issuecomment-1444810705
> The soft limit of 1024 would resolve issues with programs which loop through the entire file-descriptor range, and is the largest value compatible with software which uses `select(2)`.

> `Invalid argument in select()`.

Also, I have this issue with docker and limits on my local host. So I have to rebuild the packages against the latest go version.

**Comment by toots** [comment]
Hi! There was a file descriptor leak with SSL in `v2.1.4`. Any chance you could try with `rolling-release-v2.2.x`? Please note that the syntax for using SSL has changed there, see: https://www.liquidsoap.info/doc-dev/harbor_http.html#https-support

**Comment by brenc** [comment]
@toots that would make sense. I started to upgrade to 2.2 but had to roll back. Will stay at 2.1.3 for now.

**Comment by vitoyucepi** [comment]
Hi @toots,
I suppose you're talking about #3067. I don't think this is the case.
Could you create a build that will print traces for these events?
> `Error while reading from client: Invalid argument in select()`
> `Metadata update may have failed with error: Invalid argument in select()`

**Comment by vitoyucepi** [comment]
@toots, I've expected these changes in *2.1.x* branch, because @brenc can reproduce this issue only with *2.1.4* (*2.1.3* is fine).

**Comment by toots** [comment]
Hmm. It's gonna be complicated to rebuild `v2.1.4` through the actions. If @brenc can compile locally via opam I'm happy to provide a patch but, at this point, we're very close to the `2.2.0` release so I'd rather focus on fixing the issue there, if it exists..

**Comment by brenc** [comment]
@toots all good. I'm just about done moving to 2.2.

**Comment by brenc** [comment]
This appears to be fixed in 2.2.x.

**Comment by brenc** [comment]
Spoke too soon. Rolled out to production and within a day LS started logging this:

```
[/radio_mp3:3] Connecting mount /radio.mp3 for radio@10.0.23.45...                                                      
[/radio_mp3:2] Connection failed: Unix.Unix_error(Unix.EINVAL, "select", "")
[/radio_mp3:3] Will try again in 3.00 sec
```

Also metadata updates fail:
```
[/radio_mp3.2:2] Metadata update may have failed with error: Unix.Unix_error(Unix.EINVAL, "select", "")
```

It's possible this is due to an error condition (and possibly resource exhaustion?). I see one of the Icecast servers was unreachable (we have three instances). This happened for a number of hours before the select errors started:
```
[/radio_mp3:3] Connecting mount /radio.mp3 for radio@10.0.23.45...
[/radio_mp3:2] Connection failed: could not write data to host: Unix.Unix_error(Unix.EHOSTUNREACH, "write", "")
[/radio_mp3:3] Will try again in 3.00 sec.
```

I fixed that and will see if this happens again.

**Comment by brenc** [comment]
OK so this happened again during normal running conditions. I'm seeing this regularly:

```
[/radio_mp3.3:2] Metadata update may have failed with error: Unix.Unix_error(Unix.EINVAL, "select", "")
```

And I'm seeing this if I try to connect to stream w/ butt:
```
[input.harbor.2:3] Decoding...
[input.harbor.2:2] Error while reading from client: Unix.Unix_error(Unix.EINVAL, "select", "")
[input.harbor.2:2] Feeding stopped: Avutil.Error(Invalid data found when processing input).
```

This doesn't seem to happen in dev/staging now. The only real difference that I can think of there is that listeners aren't connecting / disconnecting regularly on these envs.

Double checked some resource usage like open files. That doesn't seem to be an issue.
```
# cat /proc/2845871/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             unlimited            unlimited            processes 
Max open files            1048576              1048576              files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       256745               256745               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us
```

Currently LS has about 3K open files which seems high considering we have just one listener at the moment.

I increased logging to 4 so we'll see if that produces any interesting output.

**Comment by toots** [comment]
Yeah this looks like a fd leak. Could you check:
```shell
ls -l /proc/<pid>/fd
```

**Comment by brenc** [comment]
Yep looks like that's what it is. Here is some additional logging:
```
[harbor:4] Client logged in.                                                                                                                               
[harbor:4] PUT (source) request on /radio.
[harbor:4] Adding source on mountpoint "/radio" with type "audio/mpeg".
[decoder:4] Available decoders:                                                                                                                            
[decoder:4] ffmpeg (priority: 10)                                            
[decoder:4] mad (priority: 1)                                                                                                                              
[decoder:4] Selected decoder ffmpeg for mime-type audio/mpeg with expected content {audio=pcm(stereo)}
[threads:4] Created thread "harbor source feeding" (2 total).
[input.harbor.2:3] Decoding...                                                                                                                             
[input.harbor.2:2] Error while reading from client: Unix.Unix_error(Unix.EINVAL, "select", "")
[input.harbor.2:4] Raised by primitive operation at Unix in file "unix.ml" (inlined), line 402, characters 0-161
[input.harbor.2:4] Called from Tutils.wait_for.wait in file "src/core/tools/tutils.ml", line 345, characters 10-30
[input.harbor.2:4] Called from Harbor_input.http_input_server#feed.read.(fun).f in file "src/core/sources/harbor_input.ml", line 99, characters 24-110
[input.harbor.2:4] Called from Harbor_input.http_input_server#feed.read.(fun) in file "src/core/sources/harbor_input.ml", line 106, characters 20-24       
[input.harbor.2:4]                                                                                                                                         
[input.harbor.2:2] Feeding stopped: Avutil.Error(Invalid data found when processing input).
[threads:4] Thread "harbor source feeding" terminated (1 remaining).
```

Currently 1138 open files so definitely over that soft limit.

**Comment by brenc** [comment]
Here are the metadata update failure logs:
```
[/radio_mp3.3:2] Metadata update may have failed with error: Unix.Unix_error(Unix.EINVAL, "select", "")                                                             
[/radio_mp3.3:4] Raised by primitive operation at Unix in file "unix.ml" (inlined), line 402, characters 0-161                                                      [/radio_mp3.3:4] Called from Cry.connect_sockaddr.check_timeout in file "src/cry.ml", line 141, characters 24-58                                                    [/radio_mp3.3:4] Re-raised at Cry.connect_sockaddr in file "src/cry.ml", line 164, characters 4-38                                                                  
[/radio_mp3.3:4] Called from Http.unix_transport.object#connect in file "src/core/tools/http.ml", line 50, characters 15-64                                         [/radio_mp3.3:4] Called from Cry.manual_update_metadata in file "src/cry.ml", line 693, characters 4-73                                                             [/radio_mp3.3:4] Called from Icecast2.output#insert_metadata in file "src/core/outputs/icecast2.ml", line 501, characters 16-12
```

**Comment by brenc** [comment]
Looks like it's mostly socket connections:

```
lrwx------ 1 2002 2002 64 Jul  7 15:17 32 -> 'socket:[264092829]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 33 -> 'socket:[264093918]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 34 -> 'socket:[264082258]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 35 -> 'socket:[264088139]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 36 -> 'socket:[264091087]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 37 -> 'socket:[264092711]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 38 -> 'socket:[264093066]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 39 -> 'socket:[264083326]'
l-wx------ 1 2002 2002 64 Jul  7 15:17 4 -> 'pipe:[264075097]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 40 -> 'socket:[264090274]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 41 -> 'socket:[264093431]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 42 -> 'socket:[264109195]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 43 -> 'socket:[264110129]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 44 -> 'socket:[264112264]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 45 -> 'socket:[264109240]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 46 -> 'socket:[264109356]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 47 -> 'socket:[264107606]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 48 -> 'socket:[264109399]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 49 -> 'socket:[264112017]'
lr-x------ 1 2002 2002 64 Jul  7 15:17 5 -> 'pipe:[264075098]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 50 -> 'socket:[264116483]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 51 -> 'socket:[264122632]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 52 -> 'socket:[264121766]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 53 -> 'socket:[264124590]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 54 -> 'socket:[264117934]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 55 -> 'socket:[264116974]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 56 -> 'socket:[264137810]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 57 -> 'socket:[264139037]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 58 -> 'socket:[264137046]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 59 -> 'socket:[264136209]'
l-wx------ 1 2002 2002 64 Jul  7 15:00 6 -> 'pipe:[264075098]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 60 -> 'socket:[264139385]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 61 -> 'socket:[264139360]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 62 -> 'socket:[264141345]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 63 -> 'socket:[264135470]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 64 -> 'socket:[264132157]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 65 -> 'socket:[264131416]'
lrwx------ 1 2002 2002 64 Jul  7 15:17 66 -> 'socket:[264131446]'
```

**Comment by vitoyucepi** [comment]
Hi @brenc,
How many sockets are opened?
`ls -l "/proc/$(pidof liquidsoap)/fd" | wc -l`

**Comment by brenc** [comment]
When the errors are happening it's always about 1080 FDs. Less than 1100 but more than 1024. I can watch the number of open FDs steadily grow until this point.

**Comment by toots** [comment]
Thanks! I'm gonna review the code to see if I can spot it. 

Is your script still:
```liquidsoap
settings.log.level.set(6)

a = input.harbor(
  "radio",
  port=8001,
  user="source",
  password="hackme",
  buffer=6.0,
  timeout=10.0,
)

output.icecast(
  %mp3,
  mksafe(a),
  user="source",
  password="hackme",
  mount="/radio",
  host="icecast",
  port=8000,
)
```
How often does the DJ connect to `input.harbor`?

**Comment by brenc** [comment]
More or less yes. The DJ rarely ever connects. I have an API that gets connections 1-3+/s though. The proxy server connects to check if the API is up and running every second and things like that. I think that's part of what's causing this.

Been meaning to whip up a simple config to see if I can recreate this. Will try that now.

**Comment by brenc** [comment]
Right now there are 1319 FDs. I think the number might continue to increase until I restart LS.

**Comment by toots** [comment]
Thanks for your patience. I believe that this is fixed now. A cleanup call got deleted when handling redirections in our internal `http` handlers. If we ever have a bugfix for `2.1.x` this will surely be in it.

**Comment by brenc** [comment]
OK so this isn't fixed. FDs continue to increase until LS stops operating. Some additional observations once open FDs get to above 1000:
- LS doesn't appear to crash but it does stop streaming audio, getting new tracks to play, etc. The station reports as being down (Icecast off-air message).
- LS _does_ still respond to requests on the Harbor API I built.
- Metadata updates still fail:
```
[/radio_mp3.3:2] Metadata update may have failed with error: Unix.Unix_error(Unix.EINVAL, "select", "")
[/radio_mp3.3:4] Raised by primitive operation at Unix in file "unix.ml" (inlined), line 402, characters 0-161
[/radio_mp3.3:4] Called from Cry.connect_sockaddr.check_timeout in file "src/cry.ml", line 141, characters 24-58
[/radio_mp3.3:4] Re-raised at Cry.connect_sockaddr in file "src/cry.ml", line 164, characters 4-38
[/radio_mp3.3:4] Called from Http.unix_transport.object#connect in file "src/core/tools/http.ml", line 50, characters 15-64
[/radio_mp3.3:4] Called from Cry.manual_update_metadata in file "src/cry.ml", line 693, characters 4-73
[/radio_mp3.3:4] Called from Icecast2.output#insert_metadata in file "src/core/outputs/icecast2.ml", line 505, characters 16-128
```
- I can still connect with butt via Harbor SSL though. This doesn't seem to change anything. It accepts input but the station is still down. Eventually LS spits out this:
`[input.harbor.2:4] Generator max length exeeded (882000 < 883152)! Dropping content..`
- On production, after I connected via butt and then disconnected it was spitting this out continually until I restarted it. There were over 40K open FDs at the time.
`[harbor:2] Failed to accept new client: SSL accept() error: error:00000000:lib(0)::reason(0)`
- As far as I know, the client wasn't trying to reconnect.
- I'm no longer getting select errors when I connect with butt.
- I think I can get this to happen more quickly if I set a `thread.run` to make a simple HTTP GET request to an endpoint that returns a 200 ever 0.10 seconds.
- When I tried to gracefully restart LS, it wouldn't shut down. I had to hard restart it. I'm using nodemon to run LS on dev. It sends a `SIGTERM` to gracefully restart on config changes.

Continue to test and think of ways to easily recreate this.

**Comment by brenc** [comment]
Another observation: open FDs continue to rise w/o the additional `http.get` requests I was doing. It's a slow steady rise. It takes about 12-16 hours for it to reach 1000+ to where LS starts having problems.

**Comment by toots** [comment]
@brenc any chance you could provide an extract of `lsof -p <pid>`? That would give more context about the leaking FDs..

**Comment by brenc** [comment]
Yep here it is. A little over 200 open FDs right now.
[lsof_output.txt](https://github.com/savonet/liquidsoap/files/12008540/lsof_output.txt)

**Comment by brenc** [comment]
Looks like this piece of code here is the culprit. If I uncomment this, FDs/open sockets increase:
```
let ngr.inputs.harbor_ssl = input.harbor(
  "radio",
  buffer=6.0,
  port=8000,
  timeout=10.0,
  transport=ngr.transports.ssl,
  user=icecast_mount_radio_usr,
  password=icecast_mount_radio_psw,
)
```
Here's the transport:
```
let ngr.transports = ()

let ngr.transports.ssl = http.transport.ssl(
  certificate="/app/star_newgroundsradio_com.cert",
  key="/app/star_newgroundsradio_com.key",
)
```
Non-SSL Harbor doesn't do this.

**Comment by toots** [comment]
Thanks. I'm running this:

### server
```liquidsoap
settings.log.level.set(4)

transport = http.transport.ssl(
  certificate="/tmp/ssl.cert",
  key="/tmp/ssl.key"
)

a = input.harbor(
  "radio",
  transport=transport,
  port=8001,
  user="source",
  password="hackme",
  buffer=6.0,
  timeout=10.0,
)

output.dummy(fallible=true, a)
```

### client
```liquidsoap
s = playlist("/tmp/playlists")

s = insert_metadata(s)

counter = ref(0)

thread.run(every=1., {begin
  s.insert_metadata([("title","counter #{counter()}")])
  counter.set(counter()+1)
end})

transport = http.transport.ssl(
  certificate="/tmp/ssl.cert",
  key="/tmp/ssl.key"
)

output.icecast(
  transport=transport,
  fallible=true,
  port=8001,
  mount="radio",
  %mp3,
  s
)
```
To see if I can reproduce.

**Comment by brenc** [comment]
OK I have *finally* figured out how to replicate this reliably. Using the following config:
```
settings.log.file.set(false)
settings.log.level.set(3)
settings.log.stdout.set(true)

ssl_transport = http.transport.ssl(
  certificate="cert.pem",
  key="key.pem",
)

harbor_ssl = input.harbor(
  "radio",
  buffer=6.0,
  port=8000,
  timeout=10.0,
  transport=ssl_transport,
  user="radio",
  password="radio",
)

output.dummy(sine(440.))
```
In one window run:
```
watch -n1 'ls /proc/$(pidof liquidsoap)/fd | wc -l'
```
In another run:
```
openssl s_client -connect HOST:PORT
```
When you connect, you'll see the FD/socket count increment. If you do a normal request i.e.:
```
HEAD / HTTP/1.1
[hit enter]
```
After it disconnects you'll then see the FD count decrement as expected. However, if you connect and immediately press  ctrl-c to disconnect you'll see the socket count increment but not decrement.

What causes this in production is the health check in haproxy. I use a TCP frontend to proxy SSL requests to LS. It could be that the health check sometimes disconnects itself abnormally/prematurely which would explain why the FD count increments slowly over time.

The health check runs every 2 seconds to see if the port is responding but it doesn't consistently increment the FD count. My theory is that it doesn't always close the connection cleanly which is triggering this bug. If I disable the health check, FD count stays steady.

Interestingly, if I simply telnet to the port then ctrl-c the FD gets cleaned up properly. So it seems that the connection has to go through the SSL negotiation first.

**Comment by vitoyucepi** [comment]
@brenc, after researching the file limit problem, I have concluded that setting the soft limit to 1024 will be better. Potentially it can prevent some unexpected segfault or memory corruption related to Linux `select` function.

@toots, did I come to the correct conclusion? Is it possible to move away from `select`?

**Comment by toots** [comment]
@vitoyucepi everything is switched to `poll` whenever available now!

**Comment by toots** [comment]
After some serious digging by @brenc and a full reproduction setup at https://github.com/brenc/lsfdbug it would appear that this bug is now closed!
